# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test-code:

    runs-on: ubuntu-latest
    
    services:
        postgres_db:
          image: postgres
          env:
            POSTGRES_USER: politics
            POSTGRES_PASSWORD: politics
            POSTGRES_DB: politics
          ports:
           - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
      env: 
        OAUTH2_CLIENT_SECRET: ${{ secrets.OAUTH2_CLIENT_SECRET }}
    - name: Build with Maven
      run: mvn -B test -Dspring.profiles.active=githubActions
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
