# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
      env: 
        OAUTH2_CLIENT_SECRET: ${{ secrets.OAUTH2_CLIENT_SECRET }}
    - name: Build with Maven
      run: mvn test -Dspring.profiles.active=githubActions
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      
  deploy-heroku:
  
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test-code
    
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "politicians-fear" #Must be unique in Heroku
          heroku_email: "lucenaalmirjames123@gmail.com"
